# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created: Thu Apr 24 22:36:56 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import wof, Discount, Service, Tyres, Parts, Labour, Full_payment, Partial_payment
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1068, 909)
        self.tableWidget = QtGui.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(20, 370, 971, 201))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 274, 63))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.verticalLayout_5.addWidget(self.lineEdit_7)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.verticalLayout_5.addWidget(self.comboBox_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(650, 10, 337, 30))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(660, 40, 221, 331))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_7.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("StoneSans"))
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.verticalLayout_7.addWidget(self.pushButton_11)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 90, 246, 116))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.layoutWidget4 = QtGui.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 330, 224, 30))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_12 = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.pushButton_13 = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_6.addWidget(self.pushButton_13)
        self.layoutWidget5 = QtGui.QWidget(Form)
        self.layoutWidget5.setGeometry(QtCore.QRect(540, 590, 441, 261))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_14 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_18 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_8.addWidget(self.label_19)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_15 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_9.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_9.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_9.addWidget(self.label_17)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pushButton_17 = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.verticalLayout_13.addWidget(self.pushButton_17)
        self.pushButton_14 = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.verticalLayout_13.addWidget(self.pushButton_14)
        self.pushButton_15 = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.verticalLayout_13.addWidget(self.pushButton_15)
        self.pushButton_16 = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.verticalLayout_13.addWidget(self.pushButton_16)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_20 = QtGui.QLabel(self.layoutWidget5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_8.addWidget(self.label_20)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_21 = QtGui.QLabel(self.layoutWidget5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_9.addWidget(self.label_21)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_9.addWidget(self.lineEdit_9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(30, 620, 268, 237))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_3)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_2.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textEdit_3 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.gridLayout_3.addWidget(self.textEdit_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(890, 150, 131, 21))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(300, 91, 345, 235))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_11 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_10 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_4.addWidget(self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.widget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.verticalLayout_4.addWidget(self.comboBox_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout_4.addWidget(self.lineEdit_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.verticalLayout_15.addLayout(self.verticalLayout_11)
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_15.addWidget(self.checkBox)

        self.retranslateUi(Form)
        self.conn()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Add", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Description", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Qty", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Unit", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Amount", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Amount(GST)", None))
        self.label.setText(_translate("Form", "INVOICE NO. IN", None))
        self.label_12.setText(_translate("Form", "Date:", None))
        self.pushButton_3.setText(_translate("Form", "Preview", None))
        self.pushButton_2.setText(_translate("Form", "Print", None))
        self.pushButton_4.setText(_translate("Form", "EMAIL", None))
        self.pushButton_5.setText(_translate("Form", "WOF", None))
        self.pushButton_6.setText(_translate("Form", "Service", None))
        self.pushButton_7.setText(_translate("Form", "Tyres", None))
        self.pushButton_8.setText(_translate("Form", "Parts", None))
        self.pushButton_9.setText(_translate("Form", "Labour", None))
        self.pushButton_10.setText(_translate("Form", "Wheel Alignment", None))
        self.pushButton_11.setText(_translate("Form", "Panel Painting Labour", None))
        self.label_5.setText(_translate("Form", "Customer Detail", None))
        self.label_2.setText(_translate("Form", "Name:", None))
        self.label_3.setText(_translate("Form", "Tel:", None))
        self.label_4.setText(_translate("Form", "Address:", None))
        self.pushButton_12.setIcon(QtGui.QIcon("icons/plus.jpeg"))
        self.pushButton_13.setIcon(QtGui.QIcon("icons/min.jpeg"))
        self.label_14.setText(_translate("Form", "Total:", None))
        self.label_18.setText(_translate("Form", "GST:", None))
        self.label_19.setText(_translate("Form", "Total:", None))
        self.label_15.setText(_translate("Form", "TextLabel", None))
        self.label_16.setText(_translate("Form", "TextLabel", None))
        self.label_17.setText(_translate("Form", "TextLabel", None))
        self.pushButton_17.setText(_translate("Form", "Discount", None))
        self.pushButton_14.setText(_translate("Form", "Full Payment", None))
        self.pushButton_15.setText(_translate("Form", "Partial Payment", None))
        self.pushButton_16.setText(_translate("Form", "Clear Payment", None))
        self.label_20.setText(_translate("Form", "Paid:", None))
        self.label_21.setText(_translate("Form", "Amount Due:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Note", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Service", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Labour", None))
        self.checkBox_2.setText(_translate("Form", "Fit & Balance", None))
        self.label_6.setText(_translate("Form", "Vehicle Detail", None))
        self.label_7.setText(_translate("Form", "Make:", None))
        self.label_8.setText(_translate("Form", "Model:", None))
        self.label_9.setText(_translate("Form", "REGO:", None))
        self.label_11.setText(_translate("Form", "VIN:", None))
        self.label_10.setText(_translate("Form", "Oddometer:", None))
        self.pushButton.setText(_translate("Form", "Match", None))
        self.checkBox.setText(_translate("Form", "Trailer", None))




    def conn(self):
        QtGui.QWidget.connect(self.pushButton_5, QtCore.SIGNAL("clicked()"), self.wof)
        QtGui.QWidget.connect(self.pushButton_17, QtCore.SIGNAL("clicked()"), self.discount)
        QtGui.QWidget.connect(self.pushButton_6, QtCore.SIGNAL("clicked()"), self.service)
        QtGui.QWidget.connect(self.pushButton_7, QtCore.SIGNAL("clicked()"), self.tyres)
        QtGui.QWidget.connect(self.pushButton_8, QtCore.SIGNAL("clicked()"), self.parts)
        QtGui.QWidget.connect(self.pushButton_9, QtCore.SIGNAL("clicked()"), self.labour)
        QtGui.QWidget.connect(self.pushButton_14, QtCore.SIGNAL("clicked()"), self.full)
        QtGui.QWidget.connect(self.pushButton_15, QtCore.SIGNAL("clicked()"), self.partial)
    def wof(self):
        self.wof = QtGui.QWidget()
        self.ui = wof.Ui_Form()
        self.ui.setupUi(self.wof)
        self.wof.show()

    def partial(self):
        self.partial= QtGui.QWidget()
        self.ui = Partial_payment.Ui_Form()
        self.ui.setupUi(self.partial)
        self.partial.show()

    def full(self):
        self.full = QtGui.QWidget()
        self.ui = Full_payment.Ui_Form()
        self.ui.setupUi(self.full)
        self.full.show()

    def labour(self):
        self.labour = QtGui.QWidget()
        self.ui = Labour.Ui_Form()
        self.ui.setupUi(self.labour)
        self.labour.show()

    def parts(self):
        self.parts = QtGui.QWidget()
        self.ui = Parts.Ui_Form()
        self.ui.setupUi(self.parts)
        self.parts.show()

    def service(self):
        self.service = QtGui.QWidget()
        self.ui = Service.Ui_Form()
        self.ui.setupUi(self.service)
        self.service.show()

    def tyres(self):
        self.types = QtGui.QWidget()
        self.ui = Tyres.Ui_Form()
        self.ui.setupUi(self.types)
        self.types.show()
    def discount(self):
        self.discount = QtGui.QWidget()
        self.ui = Discount.Ui_Form()
        self.ui.setupUi(self.discount)
        self.discount.show()


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

