# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(982, 893)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(24)
        Dialog.setFont(font)
        Dialog.setStyleSheet(_fromUtf8("#Dialog {\n"
"   background-color: rgb(255, 255, 204);\n"
"   color: #cccccc;\n"
"}\n"
"QComboBox {\n"
"    background-color:rgb(153, 204, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(34, 185, 255);\n"
"    border-width: 2px;\n"
"    border-color: rgb(117, 156, 195);\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"    alternate-background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(122, 163, 204);\n"
"}\n"
"QTreeView {\n"
"   background-color: #666666;\n"
"   color: #cccccc;\n"
"   alternate-background-color: #333333;\n"
"} \n"
"QListView {\n"
"   background-color: #333333;\n"
"   color: #cccccc;\n"
"}\n"
"QTextEdit {\n"
"   color: rgb(0, 0, 0);\n"
"}\n"
"QScrollBar:horizontal {\n"
"   height: 20px;\n"
"}\n"
"QScrollBar:vertical {\n"
"   width: 20px;\n"
"}\n"
"QTabWidget::pane {\n"
"   border-top: 2px solid #cccccc;\n"
"}\n"
"QLabel {\n"
"   color: rgb(102, 102, 102); \n"
"}\n"
"\n"
"QCheckBox {\n"
"   color: white; \n"
"}\n"
"\n"
"QRadioButton{\n"
"   color:white;\n"
"}"))
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBox_make = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.comboBox_make.setFont(font)
        self.comboBox_make.setStyleSheet(_fromUtf8("QComboBox {\n"
"    background-color:rgb(255, 245, 245)\n"
"}"))
        self.comboBox_make.setEditable(True)
        self.comboBox_make.setObjectName(_fromUtf8("comboBox_make"))
        self.gridLayout_4.addWidget(self.comboBox_make, 0, 1, 1, 1)
        self.label_make = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_make.setFont(font)
        self.label_make.setObjectName(_fromUtf8("label_make"))
        self.gridLayout_4.addWidget(self.label_make, 0, 0, 1, 1)
        self.pushButton_match = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        self.pushButton_match.setFont(font)
        self.pushButton_match.setObjectName(_fromUtf8("pushButton_match"))
        self.gridLayout_4.addWidget(self.pushButton_match, 2, 2, 1, 1)
        self.label_model = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_model.setFont(font)
        self.label_model.setObjectName(_fromUtf8("label_model"))
        self.gridLayout_4.addWidget(self.label_model, 1, 0, 1, 1)
        self.label_rego = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_rego.setFont(font)
        self.label_rego.setObjectName(_fromUtf8("label_rego"))
        self.gridLayout_4.addWidget(self.label_rego, 2, 0, 1, 1)
        self.lineEdit_rego = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_rego.setFont(font)
        self.lineEdit_rego.setObjectName(_fromUtf8("lineEdit_rego"))
        self.gridLayout_4.addWidget(self.lineEdit_rego, 2, 1, 1, 1)
        self.label_oddo = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_oddo.setFont(font)
        self.label_oddo.setObjectName(_fromUtf8("label_oddo"))
        self.gridLayout_4.addWidget(self.label_oddo, 3, 0, 1, 1)
        self.lineEdit_oddo = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_oddo.setFont(font)
        self.lineEdit_oddo.setObjectName(_fromUtf8("lineEdit_oddo"))
        self.gridLayout_4.addWidget(self.lineEdit_oddo, 3, 1, 1, 1)
        self.comboBox_model = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.comboBox_model.setFont(font)
        self.comboBox_model.setStyleSheet(_fromUtf8("QComboBox {\n"
"    background-color:rgb(255, 245, 245)\n"
"}"))
        self.comboBox_model.setEditable(True)
        self.comboBox_model.setObjectName(_fromUtf8("comboBox_model"))
        self.gridLayout_4.addWidget(self.comboBox_model, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 3, 1, 1, 4)
        self.comboBox_service = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        self.comboBox_service.setFont(font)
        self.comboBox_service.setObjectName(_fromUtf8("comboBox_service"))
        self.comboBox_service.addItem(_fromUtf8(""))
        self.comboBox_service.addItem(_fromUtf8(""))
        self.comboBox_service.addItem(_fromUtf8(""))
        self.comboBox_service.addItem(_fromUtf8(""))
        self.comboBox_service.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_service, 2, 2, 1, 1)
        self.pushButton_labour = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_labour.setFont(font)
        self.pushButton_labour.setObjectName(_fromUtf8("pushButton_labour"))
        self.gridLayout_5.addWidget(self.pushButton_labour, 2, 4, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_Add = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        self.pushButton_Add.setFont(font)
        self.pushButton_Add.setObjectName(_fromUtf8("pushButton_Add"))
        self.horizontalLayout_6.addWidget(self.pushButton_Add)
        self.pushButton_Del = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        self.pushButton_Del.setFont(font)
        self.pushButton_Del.setObjectName(_fromUtf8("pushButton_Del"))
        self.horizontalLayout_6.addWidget(self.pushButton_Del)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_name = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setObjectName(_fromUtf8("label_name"))
        self.verticalLayout_2.addWidget(self.label_name)
        self.label_tel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_tel.setFont(font)
        self.label_tel.setObjectName(_fromUtf8("label_tel"))
        self.verticalLayout_2.addWidget(self.label_tel)
        self.label_addr = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_addr.setFont(font)
        self.label_addr.setObjectName(_fromUtf8("label_addr"))
        self.verticalLayout_2.addWidget(self.label_addr)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit_username = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName(_fromUtf8("lineEdit_username"))
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.lineEdit_tel = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_tel.setFont(font)
        self.lineEdit_tel.setObjectName(_fromUtf8("lineEdit_tel"))
        self.verticalLayout.addWidget(self.lineEdit_tel)
        self.lineEdit_addr = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_addr.setFont(font)
        self.lineEdit_addr.setObjectName(_fromUtf8("lineEdit_addr"))
        self.verticalLayout.addWidget(self.lineEdit_addr)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 3, 0, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_show_sub_total = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_show_sub_total.setFont(font)
        self.label_show_sub_total.setObjectName(_fromUtf8("label_show_sub_total"))
        self.verticalLayout_8.addWidget(self.label_show_sub_total)
        self.label_show_gst = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_show_gst.setFont(font)
        self.label_show_gst.setObjectName(_fromUtf8("label_show_gst"))
        self.verticalLayout_8.addWidget(self.label_show_gst)
        self.label_show_total = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_show_total.setFont(font)
        self.label_show_total.setObjectName(_fromUtf8("label_show_total"))
        self.verticalLayout_8.addWidget(self.label_show_total)
        self.label_show_after_discount = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.label_show_after_discount.setFont(font)
        self.label_show_after_discount.setObjectName(_fromUtf8("label_show_after_discount"))
        self.verticalLayout_8.addWidget(self.label_show_after_discount)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_sub_total = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sub_total.setFont(font)
        self.label_sub_total.setObjectName(_fromUtf8("label_sub_total"))
        self.verticalLayout_9.addWidget(self.label_sub_total)
        self.label_gst = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_gst.setFont(font)
        self.label_gst.setObjectName(_fromUtf8("label_gst"))
        self.verticalLayout_9.addWidget(self.label_gst)
        self.label_total = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_total.setFont(font)
        self.label_total.setObjectName(_fromUtf8("label_total"))
        self.verticalLayout_9.addWidget(self.label_total)
        self.label_after_discount = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.label_after_discount.setFont(font)
        self.label_after_discount.setObjectName(_fromUtf8("label_after_discount"))
        self.verticalLayout_9.addWidget(self.label_after_discount)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pushButton_discount = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(10)
        self.pushButton_discount.setFont(font)
        self.pushButton_discount.setObjectName(_fromUtf8("pushButton_discount"))
        self.verticalLayout_13.addWidget(self.pushButton_discount)
        self.pushButton_full_payment = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(10)
        self.pushButton_full_payment.setFont(font)
        self.pushButton_full_payment.setObjectName(_fromUtf8("pushButton_full_payment"))
        self.verticalLayout_13.addWidget(self.pushButton_full_payment)
        self.pushButton_payment_option = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_payment_option.setFont(font)
        self.pushButton_payment_option.setObjectName(_fromUtf8("pushButton_payment_option"))
        self.verticalLayout_13.addWidget(self.pushButton_payment_option)
        self.pushButton_cash_paid = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(10)
        self.pushButton_cash_paid.setFont(font)
        self.pushButton_cash_paid.setObjectName(_fromUtf8("pushButton_cash_paid"))
        self.verticalLayout_13.addWidget(self.pushButton_cash_paid)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_amount_paid = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.label_amount_paid.setFont(font)
        self.label_amount_paid.setObjectName(_fromUtf8("label_amount_paid"))
        self.horizontalLayout_8.addWidget(self.label_amount_paid)
        self.lineEdit_amount_paid = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_amount_paid.setFont(font)
        self.lineEdit_amount_paid.setReadOnly(True)
        self.lineEdit_amount_paid.setObjectName(_fromUtf8("lineEdit_amount_paid"))
        self.horizontalLayout_8.addWidget(self.lineEdit_amount_paid)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_amout_due = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.label_amout_due.setFont(font)
        self.label_amout_due.setObjectName(_fromUtf8("label_amout_due"))
        self.horizontalLayout_9.addWidget(self.label_amout_due)
        self.lineEdit_amount_due = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_amount_due.setFont(font)
        self.lineEdit_amount_due.setReadOnly(True)
        self.lineEdit_amount_due.setObjectName(_fromUtf8("lineEdit_amount_due"))
        self.horizontalLayout_9.addWidget(self.lineEdit_amount_due)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.gridLayout_5.addLayout(self.verticalLayout_14, 6, 1, 1, 4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_preview = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        self.pushButton_preview.setFont(font)
        self.pushButton_preview.setObjectName(_fromUtf8("pushButton_preview"))
        self.horizontalLayout_4.addWidget(self.pushButton_preview)
        self.pushButton_print = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        self.pushButton_print.setFont(font)
        self.pushButton_print.setObjectName(_fromUtf8("pushButton_print"))
        self.horizontalLayout_4.addWidget(self.pushButton_print)
        spacerItem12 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.label_12 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lineEdit_invoice_no = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.lineEdit_invoice_no.setFont(font)
        self.lineEdit_invoice_no.setReadOnly(True)
        self.lineEdit_invoice_no.setObjectName(_fromUtf8("lineEdit_invoice_no"))
        self.verticalLayout_5.addWidget(self.lineEdit_invoice_no)
        self.pushButton_date = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.pushButton_date.setFont(font)
        self.pushButton_date.setStyleSheet(_fromUtf8("QPushButton {\n"
"    background-color:rgb(255, 251, 250);\n"
"    border-width: 1px;\n"
"    border-color:rgb(199, 199, 199)\n"
"}"))
        self.pushButton_date.setText(_fromUtf8(""))
        self.pushButton_date.setObjectName(_fromUtf8("pushButton_date"))
        self.verticalLayout_5.addWidget(self.pushButton_date)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_5.addWidget(self.tableWidget, 5, 0, 1, 5)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEdit_note = QtGui.QTextEdit(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.textEdit_note.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.textEdit_note.setFont(font)
        self.textEdit_note.setObjectName(_fromUtf8("textEdit_note"))
        self.gridLayout.addWidget(self.textEdit_note, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textEdit_service = QtGui.QTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.textEdit_service.setFont(font)
        self.textEdit_service.setObjectName(_fromUtf8("textEdit_service"))
        self.gridLayout_2.addWidget(self.textEdit_service, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textEdit_labour = QtGui.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        self.textEdit_labour.setFont(font)
        self.textEdit_labour.setObjectName(_fromUtf8("textEdit_labour"))
        self.gridLayout_3.addWidget(self.textEdit_labour, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 6, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem22, 1, 0, 1, 1)
        self.pushButton_tyres = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_tyres.setFont(font)
        self.pushButton_tyres.setObjectName(_fromUtf8("pushButton_tyres"))
        self.gridLayout_5.addWidget(self.pushButton_tyres, 2, 3, 1, 1)
        self.comboBox_wof = QtGui.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(14)
        self.comboBox_wof.setFont(font)
        self.comboBox_wof.setObjectName(_fromUtf8("comboBox_wof"))
        self.comboBox_wof.addItem(_fromUtf8(""))
        self.comboBox_wof.addItem(_fromUtf8(""))
        self.comboBox_wof.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_wof, 2, 1, 1, 1)
        self.label_logo = QtGui.QLabel(Dialog)
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../project/ui/logo.jpg")))
        self.label_logo.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.gridLayout_5.addWidget(self.label_logo, 0, 3, 2, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Add Invoice", None))
        self.label_make.setText(_translate("Dialog", "Make:", None))
        self.pushButton_match.setText(_translate("Dialog", "Match", None))
        self.label_model.setText(_translate("Dialog", "Model:", None))
        self.label_rego.setText(_translate("Dialog", "REGO:", None))
        self.label_oddo.setText(_translate("Dialog", "Oddometer:", None))
        self.comboBox_service.setItemText(0, _translate("Dialog", "Service", None))
        self.comboBox_service.setItemText(1, _translate("Dialog", "Express", None))
        self.comboBox_service.setItemText(2, _translate("Dialog", "Extensive", None))
        self.comboBox_service.setItemText(3, _translate("Dialog", "Euro_Car", None))
        self.comboBox_service.setItemText(4, _translate("Dialog", "Van_4WD", None))
        self.pushButton_labour.setText(_translate("Dialog", "Labour", None))
        self.pushButton_Add.setText(_translate("Dialog", "Add", None))
        self.pushButton_Del.setText(_translate("Dialog", "Delete", None))
        self.label_5.setText(_translate("Dialog", "Customer Detail", None))
        self.label_name.setText(_translate("Dialog", "Name:", None))
        self.label_tel.setText(_translate("Dialog", "Tel:", None))
        self.label_addr.setText(_translate("Dialog", "Address:", None))
        self.label_show_sub_total.setText(_translate("Dialog", "Sub_Total:", None))
        self.label_show_gst.setText(_translate("Dialog", "GST:", None))
        self.label_show_total.setText(_translate("Dialog", "Total:", None))
        self.label_show_after_discount.setText(_translate("Dialog", "After Discount :", None))
        self.label_sub_total.setText(_translate("Dialog", "TextLabel", None))
        self.label_gst.setText(_translate("Dialog", "TextLabel", None))
        self.label_total.setText(_translate("Dialog", "TextLabel", None))
        self.label_after_discount.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_discount.setText(_translate("Dialog", "Discount", None))
        self.pushButton_full_payment.setText(_translate("Dialog", "Full Payment", None))
        self.pushButton_payment_option.setText(_translate("Dialog", "Payment Option", None))
        self.pushButton_cash_paid.setText(_translate("Dialog", "Cash Paid", None))
        self.label_amount_paid.setText(_translate("Dialog", "Amount Paid:", None))
        self.label_amout_due.setText(_translate("Dialog", "Amount Due:", None))
        self.pushButton_preview.setText(_translate("Dialog", "Preview", None))
        self.pushButton_print.setText(_translate("Dialog", "Print", None))
        self.label.setText(_translate("Dialog", "INVOICE NO. IN", None))
        self.label_12.setText(_translate("Dialog", "Date:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "No.", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Price", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Qty", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Unit", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Amount", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Amount(GST)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Note", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Service", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Labour", None))
        self.pushButton_tyres.setText(_translate("Dialog", "Tyres", None))
        self.comboBox_wof.setItemText(0, _translate("Dialog", "WOF", None))
        self.comboBox_wof.setItemText(1, _translate("Dialog", "$30", None))
        self.comboBox_wof.setItemText(2, _translate("Dialog", "$45", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

